import { mkdir, stat, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { stdin, stdout } from 'node:process';
import { createInterface } from 'node:readline/promises';
import { Command } from 'commander';

const DEFAULT_CONFIG_PATH = '.parrat/config.yaml';

/**
 * Returns true if the path exists (file, directory, or any other entry),
 * false otherwise. Used by `parrat init` to detect existing config.
 */
export async function pathExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Write a default `.parrat/config.yaml` to `configPath`.
 * Creates parent directories as needed.
 *
 * The default ships the v1 schema (version: 1) with tenant_id and audit
 * settings populated. MCP server config + claude settings are commented-out
 * templates the user fills in for LLM-driven Skills.
 */
export async function writeDefaultConfig(configPath: string): Promise<void> {
  const yaml = [
    '# Parrat configuration',
    `# Generated by \`parrat init\` on ${new Date().toISOString()}`,
    '',
    'version: 1',
    'tenant_id: default',
    '',
    '# MCP servers — uncomment and configure for LLM-driven Skills',
    '# (e.g., freshness-investigation needs a `dbt` server).',
    'mcpServers: {}',
    '#   dbt:',
    '#     command: uvx',
    '#     args: [dbt-mcp]',
    '#     env:',
    '#       DBT_PROJECT_DIR: /absolute/path/to/dbt/project',
    '#       DBT_PATH: /absolute/path/to/dbt',
    '#       PYTHONUTF8: "1"  # Required on Windows',
    '',
    'audit:',
    '  log_path: .parrat/audit.jsonl',
    '  retention_days: 90',
    '',
    'claude:',
    '  # API key from ANTHROPIC_API_KEY env var (never declared here).',
    '  model: claude-sonnet-4-6',
    '  max_turns: 6',
    '  max_tokens: 4096',
    '  temperature: 0.0',
    '',
  ].join('\n');

  await mkdir(dirname(configPath), { recursive: true });
  await writeFile(configPath, yaml, 'utf8');
}

export const initCommand = new Command('init')
  .description('Initialize a Parrat configuration in the current directory')
  .option('--config-path <path>', 'Path to write the config file', DEFAULT_CONFIG_PATH)
  .option('-f, --force', 'Overwrite existing config without prompting', false)
  .action(async (opts: { configPath: string; force: boolean }) => {
    const configPath = resolve(opts.configPath);
    console.log('Welcome to Parrat.');
    console.log('Run `parrat skills list` to see available Skills.');
    console.log('');

    if ((await pathExists(configPath)) && !opts.force) {
      const rl = createInterface({ input: stdin, output: stdout });
      try {
        const answer = await rl.question(`${configPath} already exists. Overwrite? (y/N) `);
        if (!/^y(es)?$/i.test(answer.trim())) {
          console.log('Aborted. No changes written.');
          return;
        }
      } finally {
        rl.close();
      }
    }

    await writeDefaultConfig(configPath);
    console.log(`Configuration written to ${configPath}`);

    if (process.env.ANTHROPIC_API_KEY) {
      console.log('ANTHROPIC_API_KEY is set in your environment.');
    } else {
      console.log(
        'ANTHROPIC_API_KEY not set. Run `export ANTHROPIC_API_KEY=...` before invoking Skills that call Claude.',
      );
    }
  });
